name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-actions.yaml'
  pull_request:
    branches: [ main ] 

jobs:
  Deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
      - name: Build & Deploy
        uses: actions/checkout@v2 

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo $(whoami) > info.txt
            echo $(pwd) >> info.txt
            cd /home/ec2-user/hieu_exe 
            ls -la
            git pull
            docker-compose build frontend && docker-compose up -d frontend